import React from 'react';
import {
  View,
  Text
} from 'react-native';

const Loading = () => (
  <View>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
    <Text>LOADING LOADING LOADING LOADING</Text>
  </View>
);

export default Loading;